### ISSUE TITLE
결제방식이 "월말 공제"만 고려되어 있습니다.

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/wiki#10]
현재 결제 방식은 
월말공제, 손님결제, 토큰결제를 기획했는데요.
토큰결제는 미정이라서 아직은 고려되지 않아도되지만,
손님결제에 대한 구매와 정산이 고려되어야 합니다.

**Comment by devdotlog** [comment]
@bojung-dev 
"손님결제"는 고객이 고객 폰에서 직접 구입하는 방식을 말씀하시는 거죠?

**Comment by bojung-dev** [comment]
1층에서 현재 손님결제를 어떻게하는지 이야기했엇는데, 전달이 잘안됐엇나보네요. 특별한 시나리오는 아니고, 손님결제에 대한 설명을 정리해서 올려볼게요.

**Comment by devdotlog** [comment]
@bojung-dev
손님들 오면 회사이름으로 먹는거 말씀하시는 거죠? 회사이름의 rfid만 있으면 다를게 없다고 생각해서요.

**Comment by bojung-dev** [comment]
@devdotlog 
특별히 월말공제 구매와 다를것은 없는데, 
A 이사님이 손님들 결제를 대신 해서 음료를 결제해 줄 경우,
A 이사님의 공제 금액에서 손님결제 금액은 정산이 되지 않아야 하는 예외가 있습니다.

물론,
구매이력 조회나 정산에서
월말 공제 구매 내역과 손님 결제 구매 내역이 구분이 되어야 처리가 가능합니다.

**Comment by devdotlog** [comment]
@bojung-dev 
영수증ID 발급이나 구매 시점에 구매종류(월말공재, 손님결재)를 구분할 수 있는 변수가 필요하겠네요.
손님결재로 구매된 경우는 정산시점에 정산에 포함되지 않도록.

그러면 키오스크에서는 어떤 시점에 손님결재를 선택하나요?
