### ISSUE TITLE
구매 취소 목록 API 업데이트 (for WebAdmin)

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/wiki#14]
@devdotlog @DevelopDestroyer 
https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EA%B5%AC%EB%A7%A4%EC%B7%A8%EC%86%8C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C

API에서는 
구매 취소 내역이 누구의 내역인지 "name" 필드  정보가 추가 되어야 한다.

WebAdmin에서는
내역에서 "name" column을 추가하여 목록을 출력해야 한다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
API 응답에 "name" 필드를 추가하였습니다.
```
HTTP/1.1 200 OK

[
    {
        "date": 1544437417,
        "receipt_id": "000001",
        "name": "슈퍼맨",
        "menu_name_kr": "에스프레소",
        "price": 2500,
        "dc_price": 0,
        "type": "HOT",
        "size": "REGULAR",
        "count": 5,
        "receipt_status": 1,
        "purchase_date": 1544437313,
        "cancel_date": 1544437417,
        "purchase_type": 0
    }
]
```
