### ISSUE TITLE
영수증ID를 4자리에서 6자리 변경

### ISSUE THREAD

**Issue by devdotlog** [dcblock/wiki#15]
영수증 ID 사용이 많아질것을 대비하여 영수증ID 자릿수를 6자리로 변경합니다.

AS-IS|TO-BO
------|---------
0001 |000006

**Comment by devdotlog** [comment]
업데이트하였습니다. 다음 목록의 API Response에서 receipt_id는 모두 6자리입니다.
- https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%98%81%EC%88%98%EC%A6%9D-%EB%B2%88%ED%98%B8-%EC%9A%94%EC%B2%AD
- https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EA%B5%AC%EB%A7%A4%EC%B7%A8%EC%86%8C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C
- https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90-%EA%B5%AC%EB%A7%A4-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C
- https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98-%EA%B8%B0%EA%B0%84%EB%B3%84-%EC%A0%95%EC%82%B0-%EC%A1%B0%ED%9A%8C

**Comment by bojung-dev** [comment]
확인 하였습니다.
