### ISSUE TITLE
응답 목록의 개수가 많은 API의 경우 Paging 처리 업데이트

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/wiki#16]
※ 출시 후보(Release Candidate, RC) : 1월 4일 이후 진행

(API 업데이트)
특정 사용자를 대상으로 조회는  API는 제외하고,
전체 사용자를 대상으로 조회하는 (너무 많은 목록이 한번에 요구될 것으로 예상되는) API는
Paging 구현이 되어야 한다.

(WebAdmin 업데이트)
Paging 기능이 있는 API에 대해서는 Paging을 구현해야 한다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
[사용자의 상세 정산 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98-%EC%83%81%EC%84%B8-%EC%A0%95%EC%82%B0-%EC%A1%B0%ED%9A%8C) API Response 구조는 아래와 같은데요. 여기에서 "total_price", "total_dc_price", "before_date", "after_date"  값들을 쓰지 않는다면 제거하려고 하는데. 의견 주세요

```json
{
    "name": "슈퍼맨",
    "total_price": 12500,
    "total_dc_price": 5000,
    "before_date": 1514732400,
    "after_date": 1546225199,
    "purchases": [
        {
            "date": 1544437417,
            "receipt_id": "000001",
            "name": "아쿠아맨",
            "menu_name_kr": "에스프레소",
            "price": 2500,
            "dc_price": 1000,
            "type": "HOT",
            "size": "REGULAR",
            "count": 5,
            "receipt_status": 1,
            "purchase_date": 1544437313,
            "cancel_date": 1544437417,
            "purchase_type": 0
        }
    ]
}
```

**Comment by DevelopDestroyer** [comment]
@devdotlog 
1. '사용자의 상세 정산 조회'에서 페이징을 도입해야하나요?
현재 모달으로 보여주게끔 되어있는데... 적합성 여부가...
일정기간동안 특정 사용자의 (디폴트 기간은 일단 한달입니다)
구매목록을 보여주는 것인데.. 
이 페이지를 모달이 아닌 새로운 페이지로 보여주는 것도 검토를 해보아야 겠네요.

2. "total_price", "total_dc_price", "before_date", "after_date"의 경우..  "before_date", "after_date"는 불필요하지만, 
total_price와 dc_price는 상세 정산의 요소 중 하나이므로 필요 할 것 같습니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
- 프론트에서 사용하지 않는 **before_date**와 **after_date**는 제거하겠습니다.
- `사용자의 상세 정산 조회 API`에 페이징 기능은 보류합니다.
- 추가로 `사용자의 상세 정산 조회 API`는 구매만 전달하는게 아닙니다. 일정 기간동안 사용자의 구매, 구매취소요청, 구매취소완료가 모두 전달됩니다.

**Comment by bojung-dev** [comment]
@DevelopDestroyer 
프론트에서 사용하지 않는 before_date와 after_date는 제거를 한다는 것은 왜 이지요?
태호가 상세 내역 보여줄 기간을 요청해야 하는 것 아닌가요?

**Comment by devdotlog** [comment]
@bojung-dev 
사용자의 상세 정산 조회 API Response에 불필요한 값이여서 삭제합니다. 
사용자의 상세 정산 조회 API 요청에 넣은 before, after를 Response에 넣어주고 있었습니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
다음의 API에 Page 기능을 추가하였습니다. 
- [구매취소 목록 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EA%B5%AC%EB%A7%A4%EC%B7%A8%EC%86%8C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C)
- [사용자 구매 목록 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90-%EA%B5%AC%EB%A7%A4-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C)

**Comment by devdotlog** [comment]
@DevelopDestroyer 
구매취소 목록 조회에서 페이징 기능 버그 수정

사용자의 상세 정산 조회 API에 페이징 기능 추가
- [사용자의 상세 정산 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98-%EC%83%81%EC%84%B8-%EC%A0%95%EC%82%B0-%EC%A1%B0%ED%9A%8C)

**Comment by devdotlog** [comment]
@DevelopDestroyer 
페이징 기능이 필요한 API에는 모두 추가된 상황입니다.

일회용 구매목록 URI를 이용한 내역 조회 API는 페이징 기능을 고려하지 않습니다.

**Comment by DevelopDestroyer** [comment]
현재 페이징이 요구돼는 부분에 대해서는 구현 완료한 것 같습니다.

- 사용자 수정/삭제 
- 주문취소관리
- 손님결제정산 (페이징은 됐지만, 좀 더 보완이 필요.. 데이터의 총 갯수가 요구됨)

확인 부탁드립니다.
