### ISSUE TITLE
사용자 목록 조회시 한글 깨짐현상

### ISSUE THREAD

**Issue by DevelopDestroyer** [dcblock/wiki#18]
@Beagleme 
사용자 목록 조회 요청 시 한글이 깨지는 현상이 발생합니다.

**Comment by bojung-dev** [comment]
@Beagleme 
Admin API의 응답 헤더에 Content-Type이 아래와 같이 내려옵니다.
Content-Type: application

아래와 같이 응답의 charset이 지정되어서 내려와야 하는 것 같습니다.
Content-Type: application/json;charset=UTF-8

spring boot client restful library에서 응답에 대한 body(즉, contents)를 
헤더를 참조하여 내부에서 자동으로 인코딩 처리를 해주는 것 같습니다.
해당 restful 라이브러리가 헤더를 참조하여 인코딩을 자동으로 해주지 않더라도,
charset을 지정해 주어 개발자가 응답의 charset을 확인하여 인코딩을 직접 처리하여 데이터를 사용하도록 하는 것이 정확한 방법이라고 보입니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer @Beagleme 
Caffe API 서버에서도 사용자의 정보를 확인하기 위해 RFID를 이용하여 Admin API Server 요청하는 부분이 있습니다.
https://github.com/dcblock/wiki/wiki/DCAdminAPI-%EC%A0%95%EC%9D%98#%ED%9A%8C%EC%9B%90%EC%A0%95%EB%B3%B4
Response에 한글이 포함되어 있지만, charset은 설정되어 있지 않습니다.

```json
HTTP/1.1 200 OK
Content-Type: application/json
{
  "index": 0,
  "email": "hong@digicaps.com",
  "rfid": "1234567890",
  "name": "홍길동",
  "company": "digicap",
  "leave": false,
  "regdate": 1542083153369,
  "updatedate": 1542083153369
}
```

Caffe API 서버는 다른 서버의 REST API를 사용하기 위해서 Spring5에서 제공하는 WebClient 사용하고 있습니다. 그러면 한글이 정상적으로 파싱이 됩니다. 

```java
    /**
     * Get User from AdminServer
     *
     * @param rfid
     * @return
     * @throws Exception
     */
    public UserDto getUserByRfid(String rfid) throws Exception {
        final String uri = String.format("%s/users?rfid=%s", server, rfid);

        WebClient webClient = WebClient
                .builder()
                .baseUrl(uri)
                .defaultHeader("Accept", apiVersion)
                .build();

        Mono<UserDto> result = webClient.get()
                .retrieve()
                .bodyToMono(UserDto.class);

        UserDto userByRfid = result.block();
        return userByRfid;
    }
```

위와 같이 객체매칭 방식을 사용하면 위의 인스턴스 userByRfid에는 아래와 같이 기대하는 방식대로 파싱이  됩니다.

![image](https://user-images.githubusercontent.com/6669011/50516480-5f5dfc80-0aee-11e9-9c9c-6f2c2ac73f44.png)

***

위와는 별도로 RestTemplate 이용하여 HttpClent 기능을 처리를 할때, 서버로부터 Response 내용을 String으로 변경하여 처리하는 것보다는 아래와 같이 응답 객체로 매칭하여 처리하는 것이 좋다고 생각합니다.
API Response 구조가 정의되지 않는 형태라면 String -> Json -> HashMap 으로 데이터 구조를 변경해야겠지만, 지금처럼 정해진 구조로 응답이 수신되는 형태라면 미리 선언한 객체 매칭하는 것이 단순하게 개발하기 좋다고 생각합니다.

```java
    final String uri = "http://localhost:8080/springrestexample/employees";
    RestTemplate restTemplate = new RestTemplate();
    
    try { 
        EmployeeListVO result = restTemplate.getForObject(uri, EmployeeListVO.class);
    } catch (HttpClientErrorException e) {
        // 여기에서 처리하거나 ControllerAdvice로 Global 영역에서 처리.
        int statusCode = e.getStatusCode();
    }
```
