### ISSUE TITLE
손님결제 API의 total_page 수정

### ISSUE THREAD

**Issue by devdotlog** [dcblock/wiki#27]
@DevelopDestroyer 
[손님결제 API](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%86%90%EB%8B%98%EA%B2%B0%EC%A0%9C-%EC%A0%95%EC%82%B0-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C) bug fixed
- total_pages 값이 잘못 내려가던 부분 수정

서버 로그상으로 total_pages이 1로 내려가는 UI 화면에는 10으로 출력되네요.

확인후에 수정되었으면 close 부탁드립니다.

**Comment by DevelopDestroyer** [comment]
확인완료하였습니다.
이슈를 닫습니다.
