### ISSUE TITLE
영수증 번호 method의 응답에 "company" 파라미터 추가 요청

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/wiki#3]
[영수증 번호 요청](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%98%81%EC%88%98%EC%A6%9D-%EB%B2%88%ED%98%B8-%EC%9A%94%EC%B2%AD)

HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
{
  "receipt_id": "0001",
  "name": "홍길동",
  "date": "2018-11-12T14:30:20+0900"
}

사용자 조회 정보의 "company" 정보도 추가되어야 합니다.
사용자 인증 이후에 "company"에 따른 절차가 차이가 있습니다.

**Comment by devdotlog** [comment]
네. 반영하겠습니다.

**Comment by devdotlog** [comment]
적용하였습니다.
