### ISSUE TITLE
AWS 시간에 timezone이 적용되지 않는 문제

### ISSUE THREAD

**Issue by devdotlog** [dcblock/wiki#30]
caffe, admin server가 동작 중인 AWS에 서버 시간에 +9 timezone 적용되지 않은건 인지하고 있었는데요.

이것 때문에 두가지 문제를 발견했습니다.

1. caffe API 서버의 batch 수행 시간
caffe api 서버는 매일 0시0초에 영수증 id를 초기화 합니다. 그런데 서버 시간이 9시간이 느리기 때문에 실제로 초기화하는 시간이 우리나라 아침 9시입니다.
아래 사진은 금일 아침에 구매한 사람들의 구매 정보입니다. 9시를 기준으로 그 전에 구매한 정채리와 저는 1월 31일에 구매한 것으로 나옵니다. 영수증 id도 46, 48입니다.  그리고 9시 넘어서 구매한 고병수부터 초기화된 영수증id 1사용합니다.
이렇게 되면 정산 시점에 1월 31일에 구매한 것은 빠지게 됩니다. 실제로는 2월에 구매했지만, 정산은 1월에 되는 문제가 있습니다.

![image](https://user-images.githubusercontent.com/6669011/52094220-a49baf80-2601-11e9-8c29-cde82f5707c5.png)

2. 서버로그 시간
caffe api 서버는 서버시간을 기준으로 로그를 일단위로 저장하고 있습니다. 
그런데 서버 시간이 +9 때문에 2월 1일 로그 중에 아침 9시전에 발생한 로그는 1월 31일을 확인해야 되는 문제가 있습니다.

![image](https://user-images.githubusercontent.com/6669011/52094274-df9de300-2601-11e9-9528-a1b045c5721c.png)

**Comment by bojung-dev** [comment]
시스템 시간과 관련하여 적용 전에 여러가지 찾아보았는데,
Database의 타임존 UTC를 변경하지 않는 것을 권장한다고 합니다.
글로벌 서비스에서 특정 지역 시간으로 되어있을 경우 문제의 소지가 충분합니다.

하지만, 
저희는 디지캡 직원(한국 사람)을 한정하여 사용하기 때문에 KST(ROK)로 변경하는 것으로 하겠습니다.
- 모든 서버의 운영 시스템 Timezoen=Asia/Seoul로 변경
- DBMS Timezone=ROK(Asia/Seoul)로 변경

2월1일 - 업무 마감 시간 이후에 시스템 점검/재부팅 하겠습니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer
아래의 API는 시간을 조건으로 입력
WebManager는 시간을 Seoul Timezone을 적용
- [일회용 구매목록 URI 생성 요청](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%9D%BC%ED%9A%8C%EC%9A%A9-%EA%B5%AC%EB%A7%A4%EB%AA%A9%EB%A1%9D-uri-%EC%83%9D%EC%84%B1-%EC%9A%94%EC%B2%AD)
- [누적 총액 요청](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%88%84%EC%A0%81-%EC%B4%9D%EC%95%A1-%EC%9A%94%EC%B2%AD)
- [구매취소 목록 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EA%B5%AC%EB%A7%A4%EC%B7%A8%EC%86%8C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C)
- [사용자 구매 목록 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90-%EA%B5%AC%EB%A7%A4-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C)
- [사용자의 상세 정산 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98-%EC%83%81%EC%84%B8-%EC%A0%95%EC%82%B0-%EC%A1%B0%ED%9A%8C)
- [정산 목록 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%A0%95%EC%82%B0-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C)
- [손님결제 정산 금액 조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%86%90%EB%8B%98%EA%B2%B0%EC%A0%9C-%EC%A0%95%EC%82%B0-%EA%B8%88%EC%95%A1-%EC%A1%B0%ED%9A%8C)
