### ISSUE TITLE
(기능 추가 요구) 카드 없는 사람도 먹을수 있게 해주세요

### ISSUE THREAD

**Issue by sh0seo** [dcblock/wiki#34]
> 기능 추가에 대해 직원이 요구한 것을 메모용으로 기록합니다.

**출퇴근 카드가 없는 경우에도 키오스크에서 구매할 수 있게 해달라**는 요구사항입니다.

출입카드가 없는 경우에도 본인인증만 되면 구매자체는 문제가 없음

**Comment by bojung-dev** [comment]
해당 기능은 통합 모바일 버전을 구현하게되면 가능한 부분이므로 우선 이슈를 닫겠습니다.
