### ISSUE TITLE
JWT 검증 알고리즘을 RSA를 적용하는게 어떨까요?

### ISSUE THREAD

**Issue by sh0seo** [dcblock/wiki#4]
현재 JWT 검증 방식을 AdminServer에 물어보는 방식을 사용하는데요(HMAC-SHA256).
이걸 RSA 알고리즘을 변경하는게 맞지 않을까 싶습니다.
AdminServer에게 물어보는게 아니라 공개키를 다른 서버에게 미리 제공하는 방식으로...

**Comment by bojung-dev** [comment]
@devdotlog 
지금 의견에 따라 생각해보니,
RS256(RSA SIGNATURE WITH SHA256) 서명 방식을 사용하면
토큰 발급자의 개인키로 서명한 것을
참여한 모든 이해관계자들이 필요에 따라 토큰 발급자의 공개키로 서명 검증을 할수 있는 유연성이 있겠네요.

단지 서명에 대한 검증만 토큰 발급자에게 확인 받는것 뿐이라면 각자 검증하는것도 상관은 없다고 생각이되는데, 토큰 발급자에게 다른 무언가의 정보를 다시 받아야하는 경우가 있다면,
매번 토큰에 대한 상태를 확인하는 것도 필요할 것 같기도 하지만... 현재는 그러한 구현은 없기도하고요.

**인증서버만 서명 검증 할 것이냐? VS 각자 개별 서버가 서명 검증 할 것이냐?**

**Comment by devdotlog** [comment]
@bojung-dev 
현재 상태를 유지하는 게 좋을 것 같습니다.

AdminServer가 없어도 토큰만 유효하다만 서비스에 문제 없는게 좋지 않을까라는 생각에 RSA256 알고리즘 변경 이슈를 공유했었습니다.
공개키만 있으면 각자 검증하고, 토큰은 갱신 주기를 짧게해서 처리하면 된다고 생각을 했었습니다.

다만, 유지보수 측면에서는 비효율적인건 동감합니다. 또한 현재 시점에서는 개발 시간이 더욱 중요하다고 생각됩니다. 

그래서 현재 상태(SHA256)를 유지하는게 좋을 것 같습니다.
