### ISSUE TITLE
관리자 CRUD를 위한 API메서드에서 "permission" 파라미터의 코드 의미가 무엇입니까?

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/wiki#7]
roles scope
을 보니 내부에서는 코드값을 사용한다고 정의하였는데요.

```
"admin" "ADMIN" (all access) / 내부코드 : 1000
"operator" "OPERATOR" (partial access) / 내부코드 : 2000
"user" "USER" (only read access) / 내부코드 : 3000
```

API 에서 이 코드값이 쓰이는 부분을 있는지 확인해 보다보니
```
permission:1
permission:2
```
이런 부분이 있는데, 1, 2가 의미하는 바에 대한 설명이 없습니다.
설명이 필요할 것 같습니다.

[DCAdminAPI 바로가기](https://github.com/dcblock/wiki/wiki/DCAdminAPI-%EC%A0%95%EC%9D%98)

**Comment by Beagleme** [comment]
@bojung-dev 
회의를 통해 아래와 같이 변경합니다.
permission -> scope 이름 변경
scope은 String 형태로 ADMIN, OPERATOR, USER로 사용

Wiki도 수정하여 반영하였습니다.
[DCAdminAPI](https://github.com/dcblock/wiki/wiki/DCAdminAPI-%EC%A0%95%EC%9D%98)
[데이터베이스 정의](https://github.com/dcblock/wiki/wiki/%EB%8D%B0%EC%9D%B4%ED%83%80%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%A0%95%EC%9D%98)
