### ISSUE TITLE
구매내역/주문취소 관련 API 관련 요구사항

### ISSUE THREAD

**Issue by DevelopDestroyer** [dcblock/wiki#9]
@devdotlog 

이번 PHASE에서 백오피스에 필요한 API는 다음과 같습니다. 2의 경우 구현된 것을 확인하였고,
우선 1이 만들어져야 테스트가 가능할 것 같습니다..

1. 취소요청 목록
2. 취소승인
3. 기간별 공제정산 조회
4. 특정 유저의 구매내역
5. 일회용 구매내역 조회

3번에서는 기간을 지정하여 요청할경우 응답으로 전직원의 리스트를 반환해 줍니다.
리퀘스트 파라미터는 "기간", "조회 대상 회사(DigiCAP, Covision, Both)" 등이 있을 것으로 예상 됩니다.

4번의 경우 백오피스 UI상에서 3의 내용을 리스트로 뿌려준 상태에서, 특정 직원을 클릭하면 해당 직원의 그 기간동안의 구매내역을 조회 할 수 있는 기능으로 제공할 예정입니다.

5의 경우에는... 제 쪽의 {백오피스 HOST}/my_order/{일회성 token}으로 알고있는데요,
여기로 요청이 들어오면 제 백엔드 단에서는 카페API로 어떤 정보를 날려야
구매내역 리스트를 받아볼수있나요?

**Comment by devdotlog** [comment]
@DevelopDestroyer 
1. 취소요청 목록 API는 Request, Response부터 정의하여 공유 하겠습니다(개발 그 후에).
2. 취소승인 API는 영수증 ID는 있으면 가능하기 때문에 임의로 구매를 진행하고 이 때 사용한 영수증 ID로 취소를 테스트 하면 됩니다.
3. 기간별 공제정산 조회 API는 가장 마지막에 개발하도록 하겠습니다.
4. 특정 유저의 구매내역 API는 Request, Response부터 정의하여 공유 하겠습니다.
5. 일회용 구매내역 조회 API는 해당 URL로 GET 요청하면 응답이 전달됩니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
1. 취소요청 목록
https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EA%B5%AC%EB%A7%A4%EC%B7%A8%EC%86%8C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C
4. 특정 유저의 구매목록 조회
https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90-%EA%B5%AC%EB%A7%A4-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C

Request/Response를 구성하였습니다. UI에 맞게 구성했습니다. 확인 후에 답변 주세요.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
취소요청 목록 / 특정 유저의 구매목록 API 응답을 변경하였습니다.
요청 파라미터만 차이가 있고, 응답 구조는 동일합니다.
https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EA%B5%AC%EB%A7%A4%EC%B7%A8%EC%86%8C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C

개발은 아직입니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
구매취소 목록 예제:
/api/caffe/purchases/purchase/search?after=1543600374&before=1545231600&filter=3

특정 유저의 구매목록:
/api/caffe/purchases/purchase/search?after=1543600374&before=1545231600&filter=-1&user_index=28

반영하였습니다. 확인 요청 드립니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
"3. 기간별 공제정산 조회" 용 API를 추가하였습니다.
참고로 구매목록 구조는 구매취소목록 구조와 동일합니다.
https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98-%EA%B8%B0%EA%B0%84%EB%B3%84-%EC%A0%95%EC%82%B0-%EC%A1%B0%ED%9A%8C
